site_name: PyDrocsid Documentation
site_url: https://pydrocsid.defelo.de/
repo_name: PyDrocsid/documentation
repo_url: https://github.com/PyDrocsid/documentation/
site_description: "Documentation for the PyDrocsid Framework"
site_author: https://github.com/PyDrocsid
remote_branch: gh-pages
edit_uri: ""

theme:
  name: 'material'

  font:
    text: Roboto
    code: Roboto Mono

  language: en
  direction: ltr
  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - build.py
  - literate-nav:
      nav_file: SUMMARY.md

nav:
  - 'Index': index.md

  - 'Library':
    - 'Cogs': library/cogs.md
    - 'Config': library/config.md
    - 'Database': library/database.md
    - 'Emojis': library/emojis.md
    - 'Environment Variables': library/environment.md
    - 'Logger': library/logger.md
    - 'Material Colors': library/material_colors.md
    - 'Permissions': library/permissions.md
    - 'PubSub': library/pubsub.md
    - 'Settings': library/settings.md
    - 'Translations': library/translations.md
    - 'Util Functions': library/util.md

  - 'Cogs': cogs/

  - 'PubSub Channels': pubsub.md

