site_name: PyDrocsid Documentation
site_url: https://pydrocsid.defelo.de/
repo_name: PyDrocsid/documentation
repo_url: https://github.com/PyDrocsid/documentation/
site_description: "Documentation for the PyDrocsid Framework"
site_author: https://github.com/PyDrocsid
edit_uri: https://github.com/PyDrocsid/documentation/edit/develop/docs/

theme:
  name: 'material'

  font:
    text: Roboto
    code: Roboto Mono

  language: en
  direction: ltr
  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - build.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      enable_inventory: true
      watch:
        - docs
        - build.py
        - cogs
        - library
      handlers:
        python:
          selection:
            docstring_style: sphinx
          rendering:
            show_submodules: false
            show_root_heading: true
            heading_level: 1
            docstring_section_style: list
            separate_signature: true
            show_signature_annotations: true
          import:
            - https://docs.pycord.dev/en/master/objects.inv
            - https://docs.sqlalchemy.org/en/14/objects.inv

nav:
  - 'PyDrocsid': index.md
  - 'Library': library/
  - 'Cogs': cogs/
  - 'GitHub': https://github.com/PyDrocsid
  - 'Discord': https://pydrocsid.defelo.de/discord
  - 'Matrix': https://pydrocsid.defelo.de/matrix
