name: CI

on:
  - push
  - pull_request

env:
  PYTHON_VERSION: 3.9

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Lint docs
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: .linter.yml
          args: .

# build:
#   runs-on: ubuntu-latest
#   needs: [ lint ]

#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         submodules: recursive
#         fetch-depth: 0

#     - name: Set up Python ${{ env.PYTHON_VERSION }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ env.PYTHON_VERSION }}

#     - name: Install dependencies
#       run: pip install mkdocs-material mkdocs-git-revision-date-plugin mkdocs-git-revision-date-localized-plugin

#     - name: Build
#       run: python build.py && mkdocs build

#     - name: Deploy
#       if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
#       run: mkdocs gh-deploy --force
